//
//  TPAllRouteViewController.h
//  bus
//
//  Created by iMac on 12/9/5.
//
//

#import <UIKit/UIKit.h>
#import "TFHpple.h"
#import "TFHppleElement.h"

@interface FirstLevelViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate>
{
    NSArray * allBusNameZh;
    NSArray * allBusNameEn;
    NSArray * departureNameZh;
    NSArray * destinationNameZh;
    
    NSArray * stops_0E_go, * stops_0E_back;
    NSArray * stops_0S_go, * stops_0S_back;
    NSArray * stops_1_go, * stops_1_back;
    NSArray * stops_2_go, * stops_2_back;
    NSArray * stops_3_go, * stops_3_back;
    NSArray * stops_5_go, * stops_5_back;
    NSArray * stops_9_go, * stops_9_back;
    NSArray * stops_12_go, * stops_12_back;
    NSArray * stops_14_go, * stops_14_back;
    NSArray * stops_15_go, * stops_15_back;
    NSArray * stops_18_go, * stops_18_back;
    NSArray * stops_20_go, * stops_20_back;
    NSArray * stops_21_go, * stops_21_back;
    NSArray * stops_21Express_go, * stops_21Express_back;
    NSArray * stops_22_go, * stops_22_back;
    NSArray * stops_22Shuttle_go, * stops_22Shuttle_back;
    NSArray * stops_26_go, * stops_26_back;
    NSArray * stops_28_go, * stops_28_back;
    NSArray * stops_32_go, * stops_32_back;
    NSArray * stops_32Shuttle_go, * stops_32Shuttle_back;
    NSArray * stops_33_go, * stops_33_back;
    NSArray * stops_37_go, * stops_37_back;
    NSArray * stops_38_go, * stops_38_back;
    NSArray * stops_38Shuttle_go, * stops_38Shuttle_back;
    NSArray * stops_39_go, * stops_39_back;
    NSArray * stops_39Night_go, * stops_39Night_back;
    NSArray * stops_41_go, * stops_41_back;
    NSArray * stops_42_go, * stops_42_back;
    NSArray * stops_42Shuttle_go, * stops_42Shuttle_back;
    NSArray * stops_46_go, * stops_46_back;
    NSArray * stops_49_go, * stops_49_back;
    NSArray * stops_51_go, * stops_51_back;
    NSArray * stops_52_go, * stops_52_back;
    NSArray * stops_53_go, * stops_53_back;
    NSArray * stops_62_go, * stops_62_back;
    NSArray * stops_63_go, * stops_63_back;
    NSArray * stops_68_go, * stops_68_back;
    NSArray * stops_68Sub_go, * stops_68Sub_back;
    NSArray * stops_72_go, * stops_72_back;
    NSArray * stops_74_go, * stops_74_back;
    NSArray * stops_108_go, * stops_108_back;
    NSArray * stops_109_go, * stops_109_back;
    NSArray * stops_111_go, * stops_111_back;
    NSArray * stops_201_go, * stops_201_back;
    NSArray * stops_202_go, * stops_202_back;
    NSArray * stops_202Shuttle_go, * stops_202Shuttle_back;
    NSArray * stops_203_go, * stops_203_back;
    NSArray * stops_204_go, * stops_204_back;
    NSArray * stops_205_go, * stops_205_back;
    NSArray * stops_206_go, * stops_206_back;
    NSArray * stops_207_go, * stops_207_back;
    NSArray * stops_208_go, * stops_208_back;
    NSArray * stops_208Express_go, * stops_208Express_back;
    NSArray * stops_208Shuttle_go, * stops_208Shuttle_back;
    NSArray * stops_211_go, * stops_211_back;
    NSArray * stops_212_go, * stops_212_back;
    NSArray * stops_212Shuttle_go, * stops_212Shuttle_back;
    NSArray * stops_212Express_go, * stops_212Express_back;
    NSArray * stops_212Night_go, * stops_212Night_back;
    NSArray * stops_214_go, * stops_214_back;
    NSArray * stops_214Express_go, * stops_214Express_back;
    NSArray * stops_215_go, * stops_215_back;
    NSArray * stops_216Shuttle_go, * stops_216Shuttle_back;
    NSArray * stops_216Sub_go, * stops_216Sub_back;
    NSArray * stops_218_go, * stops_218_back;
    NSArray * stops_218Express_go, * stops_218Express_back;
    NSArray * stops_218Shuttle_go, * stops_218Shuttle_back;
    NSArray * stops_220_go, * stops_220_back;
    NSArray * stops_220Express_go, * stops_220Express_back;
    NSArray * stops_220Night_go, * stops_220Night_back;
    NSArray * stops_221_go, * stops_221_back;
    NSArray * stops_222_go, * stops_222_back;
    NSArray * stops_223_go, * stops_223_back;
    NSArray * stops_224_go, * stops_224_back;
    NSArray * stops_225_go, * stops_225_back;
    NSArray * stops_225Shuttle_go, * stops_225Shuttle_back;
    NSArray * stops_226_go, * stops_226_back;
    NSArray * stops_227_go, * stops_227_back;
    NSArray * stops_227Shuttle_go, * stops_227Shuttle_back;
    NSArray * stops_230_go, * stops_230_back;
    NSArray * stops_231_go, * stops_231_back;
    NSArray * stops_232_go, * stops_232_back;
    NSArray * stops_232Fast_go, * stops_232Fast_back;
    NSArray * stops_232Sub_go, * stops_232Sub_back;
    NSArray * stops_234_go, * stops_234_back;
    NSArray * stops_235_go, * stops_235_back;
    NSArray * stops_236_go, * stops_236_back;
    NSArray * stops_236Shuttle_go, * stops_236Shuttle_back;
    NSArray * stops_236Night_go, * stops_236Night_back;
    NSArray * stops_237_go, * stops_237_back;
    NSArray * stops_240_go, * stops_240_back;
    NSArray * stops_240Express_go, * stops_240Express_back;
    NSArray * stops_241_go, * stops_241_back;
    NSArray * stops_242_go, * stops_242_back;
    NSArray * stops_243_go, * stops_243_back;
    NSArray * stops_245_go, * stops_245_back;
    NSArray * stops_246_go, * stops_246_back;
    NSArray * stops_247_go, * stops_247_back;
    NSArray * stops_247Shuttle_go, * stops_247Shuttle_back;
    NSArray * stops_248_go, * stops_248_back;
    NSArray * stops_249_go, * stops_249_back;
    NSArray * stops_250_go, * stops_250_back;
    NSArray * stops_251_go, * stops_251_back;
    NSArray * stops_251Shuttle_go, * stops_251Shuttle_back;
    NSArray * stops_252_go, * stops_252_back;
    NSArray * stops_253_go, * stops_253_back;
    NSArray * stops_254_go, * stops_254_back;
    NSArray * stops_255_go, * stops_255_back;
    NSArray * stops_255Shuttle_go, * stops_255Shuttle_back;
    NSArray * stops_256_go, * stops_256_back;
    NSArray * stops_257_go, * stops_257_back;
    NSArray * stops_260_go, * stops_260_back;
    NSArray * stops_260Shuttle_go, * stops_260Shuttle_back;
    NSArray * stops_261_go, * stops_261_back;
    NSArray * stops_262_go, * stops_262_back;
    NSArray * stops_262Shuttle_go, * stops_262Shuttle_back;
    NSArray * stops_263_go, * stops_263_back;
    NSArray * stops_265Central_go, * stops_265Central_back;
    NSArray * stops_265Mingde_go, * stops_265Mingde_back;
    NSArray * stops_265Shuttle_go, * stops_265Shuttle_back;
    NSArray * stops_265Night_go, * stops_265Night_back;
    NSArray * stops_266_go, * stops_266_back;
    NSArray * stops_266Shuttle_go, * stops_266Shuttle_back;
    NSArray * stops_267_go, * stops_267_back;
    NSArray * stops_268_go, * stops_268_back;
    NSArray * stops_270_go, * stops_270_back;
    NSArray * stops_270Shuttle_go, * stops_270Shuttle_back;
    NSArray * stops_274_go, * stops_274_back;
    NSArray * stops_276_go, * stops_276_back;
    NSArray * stops_277_go, * stops_277_back;
    NSArray * stops_278_go, * stops_278_back;
    NSArray * stops_278Shuttle_go, * stops_278Shuttle_back;
    NSArray * stops_279_go, * stops_279_back;
    NSArray * stops_280_go, * stops_280_back;
    NSArray * stops_280Express_go, * stops_280Express_back;
    NSArray * stops_281_go, * stops_281_back;
    NSArray * stops_282_go, * stops_282_back;
    NSArray * stops_282Sub_go, * stops_282Sub_back;
    NSArray * stops_284_go, * stops_284_back;
    NSArray * stops_284Express_go, * stops_284Express_back;
    NSArray * stops_285_go, * stops_285_back;
    NSArray * stops_286_go, * stops_286_back;
    NSArray * stops_286Sub_go, * stops_286Sub_back;
    NSArray * stops_287_go, * stops_287_back;
    NSArray * stops_287Night_go, * stops_287Night_back;
    NSArray * stops_287Shuttle_go, * stops_287Shuttle_back;
    NSArray * stops_288_go, * stops_288_back;
    NSArray * stops_288Shuttle_go, * stops_288Shuttle_back;
    NSArray * stops_290_go, * stops_290_back;
    NSArray * stops_290Sub_go, * stops_290Sub_back;
    NSArray * stops_292_go, * stops_292_back;
    NSArray * stops_292Sub_go, * stops_292Sub_back;
    NSArray * stops_294_go, * stops_294_back;
    NSArray * stops_295_go, * stops_295_back;
    NSArray * stops_297_go, * stops_297_back;
    NSArray * stops_298_go, * stops_298_back;
    NSArray * stops_298Shuttle_go, * stops_298Shuttle_back;
    NSArray * stops_299_go, * stops_299_back;
    NSArray * stops_299Shuttle_go, * stops_299Shuttle_back;
    NSArray * stops_302_go, * stops_302_back;
    NSArray * stops_303_go, * stops_303_back;
    NSArray * stops_303Shuttle_go, * stops_303Shuttle_back;
    NSArray * stops_304Chengde_go, * stops_304Chengde_back;
    NSArray * stops_304ChongqingN_go, * stops_304ChongqingN_back;
    NSArray * stops_306_go, * stops_306_back;
    NSArray * stops_306Shuttle_go, * stops_306Shuttle_back;
    NSArray * stops_307_go, * stops_307_back;
    NSArray * stops_308_go, * stops_308_back;
    NSArray * stops_310_go, * stops_310_back;
    NSArray * stops_311_go, * stops_311_back;
    NSArray * stops_505_go, * stops_505_back;
    NSArray * stops_508_go, * stops_508_back;
    NSArray * stops_508Shuttle_go, * stops_508Shuttle_back;
    NSArray * stops_513_go, * stops_513_back;
    NSArray * stops_518_go, * stops_518_back;
    NSArray * stops_520_go, * stops_520_back;
    NSArray * stops_521_go, * stops_521_back;
    NSArray * stops_527_go, * stops_527_back;
    NSArray * stops_529_go, * stops_529_back;
    NSArray * stops_530_go, * stops_530_back;
    NSArray * stops_531_go, * stops_531_back;
    NSArray * stops_535_go, * stops_535_back;
    NSArray * stops_536_go, * stops_536_back;
    NSArray * stops_537_go, * stops_537_back;
    NSArray * stops_539_go, * stops_539_back;
    NSArray * stops_542_go, * stops_542_back;
    NSArray * stops_550_go, * stops_550_back;
    NSArray * stops_551_go, * stops_551_back;
    NSArray * stops_552_go, * stops_552_back;
    NSArray * stops_553_go, * stops_553_back;
    NSArray * stops_555_go, * stops_555_back;
    NSArray * stops_556_go, * stops_556_back;
    NSArray * stops_601_go, * stops_601_back;
    NSArray * stops_602_go, * stops_602_back;
    NSArray * stops_604_go, * stops_604_back;
    NSArray * stops_605_go, * stops_605_back;
    NSArray * stops_605Fast_go, * stops_605Fast_back;
    NSArray * stops_605Sub_go, * stops_605Sub_back;
    NSArray * stops_605Xintaiwu_go, * stops_605Xintaiwu_back;
    NSArray * stops_606_go, * stops_606_back;
    NSArray * stops_611_go, * stops_611_back;
    NSArray * stops_612_go, * stops_612_back;
    NSArray * stops_612Shuttle_go, * stops_612Shuttle_back;
    NSArray * stops_615_go, * stops_615_back;
    NSArray * stops_616_go, * stops_616_back;
    NSArray * stops_617_go, * stops_617_back;
    NSArray * stops_618_go, * stops_618_back;
    NSArray * stops_620_go, * stops_620_back;
    NSArray * stops_620Shuttle_go, * stops_620Shuttle_back;
    NSArray * stops_621_go, * stops_621_back;
    NSArray * stops_622_go, * stops_622_back;
    NSArray * stops_624_go, * stops_624_back;
    NSArray * stops_629_go, * stops_629_back;
    NSArray * stops_630_go, * stops_630_back;
    NSArray * stops_631_go, * stops_631_back;
    NSArray * stops_632_go, * stops_632_back;
    NSArray * stops_635_go, * stops_635_back;
    NSArray * stops_635Sub_go, * stops_635Sub_back;
    NSArray * stops_636_go, * stops_636_back;
    NSArray * stops_637_go, * stops_637_back;
    NSArray * stops_638_go, * stops_638_back;
    NSArray * stops_639_go, * stops_639_back;
    NSArray * stops_640_go, * stops_640_back;
    NSArray * stops_641_go, * stops_641_back;
    NSArray * stops_642_go, * stops_642_back;
    NSArray * stops_643_go, * stops_643_back;
    
    // --------------------- //
    
    NSArray * stops_644_go, * stops_644_back;
    NSArray * stops_645_go, * stops_645_back;
    NSArray * stops_645Sub_go, * stops_645Sub_back;
    NSArray * stops_646_go, * stops_646_back;
    NSArray * stops_646Shuttle_go, * stops_646Shuttle_back;
    NSArray * stops_647_go, * stops_647_back;
    NSArray * stops_648_go, * stops_648_back;
    NSArray * stops_650_go, * stops_650_back;
    NSArray * stops_651_go, * stops_651_back;
    NSArray * stops_652_go, * stops_652_back;
    NSArray * stops_656_go, * stops_656_back;
    NSArray * stops_657_go, * stops_657_back;
    NSArray * stops_658_go, * stops_658_back;
    NSArray * stops_659_go, * stops_659_back;
    NSArray * stops_660_go, * stops_660_back;
    NSArray * stops_662_go, * stops_662_back;
    NSArray * stops_663_go, * stops_663_back;
    NSArray * stops_665_go, * stops_665_back;
    NSArray * stops_666_go, * stops_666_back;
    NSArray * stops_667_go, * stops_667_back;
    NSArray * stops_668_go, * stops_668_back;
    NSArray * stops_669_go, * stops_669_back;
    NSArray * stops_670_go, * stops_670_back;
    NSArray * stops_671_go, * stops_671_back;
    NSArray * stops_672_go, * stops_672_back;
    NSArray * stops_672Shuttle_go, * stops_672Shuttle_back;
    NSArray * stops_673_go, * stops_673_back;
    NSArray * stops_675_go, * stops_675_back;
    NSArray * stops_676_go, * stops_676_back;
    NSArray * stops_677_go, * stops_677_back;
    NSArray * stops_678_go, * stops_678_back;
    NSArray * stops_679_go, * stops_679_back;
    NSArray * stops_680_go, * stops_680_back;
    NSArray * stops_681_go, * stops_681_back;
    NSArray * stops_685_go, * stops_685_back;
    NSArray * stops_701_go, * stops_701_back;
    NSArray * stops_702_go, * stops_702_back;
    NSArray * stops_705_go, * stops_705_back;
    NSArray * stops_706_go, * stops_706_back;
    NSArray * stops_711_go, * stops_711_back;
    NSArray * stops_756_go, * stops_756_back;
    NSArray * stops_902_go, * stops_902_back;
    NSArray * stops_903_go, * stops_903_back;
    NSArray * stops_905_go, * stops_905_back;
    NSArray * stops_905Sub_go, * stops_905Sub_back;
    NSArray * stops_906_go, * stops_906_back;
    NSArray * stops_906Sub_go, * stops_906Sub_back;
    NSArray * stops_907_go, * stops_907_back;
    NSArray * stops_909_go, * stops_909_back;
    NSArray * stops_912_go, * stops_912_back;
    NSArray * stops_915_go, * stops_915_back;
    NSArray * stops_M1_go, * stops_M1_back;
    NSArray * stops_M2_go, * stops_M2_back;
    NSArray * stops_M3_go, * stops_M3_back;
    NSArray * stops_M5_go, * stops_M5_back;
    NSArray * stops_M6_go, * stops_M6_back;
    NSArray * stops_M7_go, * stops_M7_back;
    NSArray * stops_M8_go, * stops_M8_back;
    NSArray * stops_M9_go, * stops_M9_back;
    NSArray * stops_M10_go, * stops_M10_back;
    NSArray * stops_M11_go, * stops_M11_back;
    NSArray * stops_M12_go, * stops_M12_back;
    NSArray * stops_M15_go, * stops_M15_back;
    NSArray * stops_JingmeiTVGHExp_go, * stops_JingmeiTVGHExp_back;
    NSArray * stops_MaokongRight_go, * stops_MaokongRight_back;
    NSArray * stops_MaokongLeftZoo_go;
    NSArray * stops_MaokongLeftTemple_go, * stops_MaokongLeftTemple_back;
    NSArray * stops_NKTianMu_go, * stops_NKTianMu_back;
    NSArray * stops_NKBeiTou_go, * stops_NKBeiTou_back;
    NSArray * stops_NKZhongheNKSBP_go, * stops_NKZhongheNKSBP_back;
    NSArray * stops_NKShuanghe_go, * stops_NKShuanghe_back;
    NSArray * stops_S31_Gong_go, * stops_S31_Gong_back;
    NSArray * stops_S31_Chong_go, * stops_S31_Chong_back;
    NSArray * stops_S1_go, * stops_S1_back;
    NSArray * stops_S1Shuttle_go, * stops_S1Shuttle_back;
    NSArray * stops_S2_go, * stops_S2_back;
    NSArray * stops_S2Shuttle_go, * stops_S2Shuttle_back;
    NSArray * stops_S3_go, * stops_S3_back;
    NSArray * stops_S3Shuttle_go, * stops_S3Shuttle_back;
    NSArray * stops_S5_go, * stops_S5_back;
    NSArray * stops_S5Shuttle_go, * stops_S5Shuttle_back;
    NSArray * stops_S6_go, * stops_S6_back;
    NSArray * stops_S7_go, * stops_S7_back;
    NSArray * stops_S8_go, * stops_S8_back;
    NSArray * stops_S9_go, * stops_S9_back;
    NSArray * stops_S10_go, * stops_S10_back;
    NSArray * stops_S11_go, * stops_S11_back;
    NSArray * stops_S12_go, * stops_S12_back;
    NSArray * stops_S12Shuttle_go, * stops_S12Shuttle_back;
    NSArray * stops_S14_go, * stops_S14_back;
    NSArray * stops_S15_go, * stops_S15_back;
    NSArray * stops_S15Shuttle_go, * stops_S15Shuttle_back;
    NSArray * stops_S16_go, * stops_S16_back;
    NSArray * stops_S17_go, * stops_S17_back;
    NSArray * stops_S18_go, * stops_S18_back;
    NSArray * stops_S18Shuttle_go, * stops_S18Shuttle_back;
    NSArray * stops_S19_go, * stops_S19_back;
    NSArray * stops_S21_go, * stops_S21_back;
    NSArray * stops_S22_go, * stops_S22_back;
    NSArray * stops_S23_go, * stops_S23_back;
    NSArray * stops_S25_go, * stops_S25_back;
    NSArray * stops_S26_go, * stops_S26_back;
    NSArray * stops_S28_go, * stops_S28_back;
    NSArray * stops_Dunhua_go, * stops_Dunhua_back;
    NSArray * stops_ZhongxiaoNML_go, * stops_ZhongxiaoNML_back;
    NSArray * stops_HepingML_go, * stops_HepingML_back;
    NSArray * stops_XinYiNML_go, * stops_XinYiNML_back;
    NSArray * stops_BoaiShuttle_go, * stops_BoaiShuttle_back;
    NSArray * stops_XinYiML_go, * stops_XinYiML_back;
    NSArray * stops_XinYiSub_go, * stops_XinYiSub_back;
    NSArray * stops_ZhongshanML_go, * stops_ZhongshanML_back;
    NSArray * stops_ChongqingML_go, * stops_ChongqingML_back;
    NSArray * stops_NH1_go, * stops_NH1_back;
    NSArray * stops_NH2_go, * stops_NH2_back;
    NSArray * stops_NH3_go, * stops_NH3_back;
    NSArray * stops_NH5_go, * stops_NH5_back;
    NSArray * stops_NH6_go, * stops_NH6_back;
    NSArray * stops_NH7_go, * stops_NH7_back;
    NSArray * stops_NH8_go, * stops_NH8_back;
    NSArray * stops_NH9_go, * stops_NH9_back;
    NSArray * stops_NH10_go, * stops_NH10_back;
    NSArray * stops_NH11_go, * stops_NH11_back;
    NSArray * stops_NH12_go, * stops_NH12_back;
    NSArray * stops_NH13_go, * stops_NH13_back;
    NSArray * stops_NH15_go, * stops_NH15_back;
    NSArray * stops_NH16_go, * stops_NH16_back;
    NSArray * stops_NH17_go, * stops_NH17_back;
    NSArray * stops_NH18_go, * stops_NH18_back;
    NSArray * stops_NH19_go, * stops_NH19_back;
    NSArray * stops_NH20_go, * stops_NH20_back;
    NSArray * stops_MRTYSNehuExp_go, * stops_MRTYSNehuExp_back;
    NSArray * stops_TaipeiCityHall_go, * stops_TaipeiCityHall_back;
    // ------------------------ 接駁公車 ------------------------
    NSArray * stops_R2_go, * stops_R2_back;
    NSArray * stops_R3_go, * stops_R3_back;
    NSArray * stops_R5_go, * stops_R5_back;
    NSArray * stops_R7_go, * stops_R7_back;
    NSArray * stops_R7Section_go, * stops_R7Section_back;
    NSArray * stops_R9_go, * stops_R9_back;
    NSArray * stops_R10_go, * stops_R10_back;
    NSArray * stops_R12_go, * stops_R12_back;
    NSArray * stops_R15_go, * stops_R15_back;
    NSArray * stops_R19_go, * stops_R19_back;
    NSArray * stops_R25_go, * stops_R25_back;
    NSArray * stops_R29_go, * stops_R29_back;
    NSArray * stops_R30_go, * stops_R30_back;
    NSArray * stops_R31_go, * stops_R31_back;
    NSArray * stops_R32_go, * stops_R32_back;
    NSArray * stops_R33_go, * stops_R33_back;
    NSArray * stops_R34_go, * stops_R34_back;
    NSArray * stops_R35_go, * stops_R35_back;
    NSArray * stops_R50_go, * stops_R50_back;
    NSArray * stops_B2_go, * stops_B2_back;
    NSArray * stops_B5_go, * stops_B5_back;
    NSArray * stops_B7_go, * stops_B7_back;
    NSArray * stops_B10_go, * stops_B10_back;
    NSArray * stops_B12_go, * stops_B12_back;
    NSArray * stops_B20Section_go, * stops_B20Section_back;
    NSArray * stops_B25_go, * stops_B25_back;
    NSArray * stops_B26_go, * stops_B26_back;
    NSArray * stops_B27_go, * stops_B27_back;
    NSArray * stops_B28_go, * stops_B28_back;
    NSArray * stops_B29_go, * stops_B29_back;
    NSArray * stops_B36_go, * stops_B36_back;
    NSArray * stops_B50_go, * stops_B50_back;
    NSArray * stops_B51_go, * stops_B51_back;
    NSArray * stops_BR1_go, * stops_BR1_back;
    NSArray * stops_BR2_go, * stops_BR2_back;
    NSArray * stops_BR3_go, * stops_BR3_back;
    NSArray * stops_BR5_go, * stops_BR5_back;
    NSArray * stops_BR6_go, * stops_BR6_back;
    NSArray * stops_BR7_go, * stops_BR7_back;
    NSArray * stops_BR9_go, * stops_BR9_back;
    NSArray * stops_BR10_go, * stops_BR10_back;
    NSArray * stops_BR11_go, * stops_BR11_back;
    NSArray * stops_BR11Sub_go, * stops_BR11Sub_back;
    NSArray * stops_BR12_go, * stops_BR12_back;
    NSArray * stops_BR13_go, * stops_BR13_back;
    NSArray * stops_BR15_go, * stops_BR15_back;
    NSArray * stops_BR15Shuttle_go, * stops_BR15Shuttle_back;
    NSArray * stops_BR16_go, * stops_BR16_back;
    NSArray * stops_BR18_go, * stops_BR18_back;
    NSArray * stops_BR19_go, * stops_BR19_back;
    NSArray * stops_BR20_go, * stops_BR20_back;
    NSArray * stops_BR21_go, * stops_BR21_back;
    NSArray * stops_G1_go, * stops_G1_back;
    NSArray * stops_G2L_go, * stops_G2L_back;
    NSArray * stops_G2R_go, * stops_G2R_back;
    NSArray * stops_G11_go, * stops_G11_back;
    // ---------------------------------------------
    NSArray * estimatetime;
    // ---------------------------------------------
    NSArray * section0Zh, * section1Zh, * section2Zh, * section3Zh, * section4Zh, * section5Zh, * section6Zh, * section7Zh, * section8Zh, * section9Zh, * section10Zh, * section11Zh, * section12Zh, * section13Zh, * section14Zh;
    NSArray * section0En, * section1En, * section2En, * section3En, * section4En, * section5En, * section6En, * section7En, * section8En, * section9En, * section10En, * section11En, * section12En, * section13En, * section14En;
    NSArray * section0Depart, * section1Depart, * section2Depart, * section3Depart, * section4Depart, * section5Depart, * section6Depart, * section7Depart, * section8Depart, * section9Depart, * section10Depart, * section11Depart, * section12Depart, * section13Depart, * section14Depart;
    NSArray * section0Destin, * section1Destin, * section2Destin, * section3Destin, * section4Destin, * section5Destin, * section6Destin, * section7Destin, * section8Destin, * section9Destin, * section10Destin, * section11Destin, * section12Destin, * section13Destin, * section14Destin;
    // ---------- UISearchBar -------------------------
    UITableView * table;
    UISearchBar * search;
    NSDictionary * allData;
    NSMutableDictionary * searchData;
    NSArray * allKeys;
    NSMutableArray * keys;
    BOOL isSearch;
    // ---------- Background appear when searchBar is tapped ----------
    UIButton * backgroundButton;
    BOOL clearNeeded;
    // ---------- dismiss keyboard when user scrolls ----------
    CGPoint startLocation;
    BOOL isScrolled;
    
}
@property (nonatomic, retain) NSArray * allBusNameZh;
@property (nonatomic, retain) NSArray * allBusNameEn;
@property (nonatomic, retain) NSArray * departureNameZh;
@property (nonatomic, retain) NSArray * destinationNameZh;

@property (nonatomic, retain) NSArray * stops_0E_go, * stops_0E_back;
@property (nonatomic, retain) NSArray * stops_0S_go, * stops_0S_back;
@property (nonatomic, retain) NSArray * stops_1_go, * stops_1_back;
@property (nonatomic, retain) NSArray * stops_2_go, * stops_2_back;
@property (nonatomic, retain) NSArray * stops_3_go, * stops_3_back;
@property (nonatomic, retain) NSArray * stops_5_go, * stops_5_back;
@property (nonatomic, retain) NSArray * stops_9_go, * stops_9_back;
@property (nonatomic, retain) NSArray * stops_12_go, * stops_12_back;
@property (nonatomic, retain) NSArray * stops_14_go, * stops_14_back;
@property (nonatomic, retain) NSArray * stops_15_go, * stops_15_back;
@property (nonatomic, retain) NSArray * stops_18_go, * stops_18_back;
@property (nonatomic, retain) NSArray * stops_20_go, * stops_20_back;
@property (nonatomic, retain) NSArray * stops_21_go, * stops_21_back;
@property (nonatomic, retain) NSArray * stops_21Express_go, * stops_21Express_back;
@property (nonatomic, retain) NSArray * stops_22_go, * stops_22_back;
@property (nonatomic, retain) NSArray * stops_22Shuttle_go, * stops_22Shuttle_back;
@property (nonatomic, retain) NSArray * stops_26_go, * stops_26_back;
@property (nonatomic, retain) NSArray * stops_28_go, * stops_28_back;
@property (nonatomic, retain) NSArray * stops_32_go, * stops_32_back;
@property (nonatomic, retain) NSArray * stops_32Shuttle_go, * stops_32Shuttle_back;
@property (nonatomic, retain) NSArray * stops_33_go, * stops_33_back;
@property (nonatomic, retain) NSArray * stops_37_go, * stops_37_back;
@property (nonatomic, retain) NSArray * stops_38_go, * stops_38_back;
@property (nonatomic, retain) NSArray * stops_38Shuttle_go, * stops_38Shuttle_back;
@property (nonatomic, retain) NSArray * stops_39_go, * stops_39_back;
@property (nonatomic, retain) NSArray * stops_39Night_go, * stops_39Night_back;
@property (nonatomic, retain) NSArray * stops_41_go, * stops_41_back;
@property (nonatomic, retain) NSArray * stops_42_go, * stops_42_back;
@property (nonatomic, retain) NSArray * stops_42Shuttle_go, * stops_42Shuttle_back;
@property (nonatomic, retain) NSArray * stops_46_go, * stops_46_back;
@property (nonatomic, retain) NSArray * stops_49_go, * stops_49_back;
@property (nonatomic, retain) NSArray * stops_51_go, * stops_51_back;
@property (nonatomic, retain) NSArray * stops_52_go, * stops_52_back;
@property (nonatomic, retain) NSArray * stops_53_go, * stops_53_back;
@property (nonatomic, retain) NSArray * stops_62_go, * stops_62_back;
@property (nonatomic, retain) NSArray * stops_63_go, * stops_63_back;
@property (nonatomic, retain) NSArray * stops_68_go, * stops_68_back;
@property (nonatomic, retain) NSArray * stops_68Sub_go, * stops_68Sub_back;
@property (nonatomic, retain) NSArray * stops_72_go, * stops_72_back;
@property (nonatomic, retain) NSArray * stops_74_go, * stops_74_back;
@property (nonatomic, retain) NSArray * stops_108_go, * stops_108_back;
@property (nonatomic, retain) NSArray * stops_109_go, * stops_109_back;
@property (nonatomic, retain) NSArray * stops_111_go, * stops_111_back;
@property (nonatomic, retain) NSArray * stops_201_go, * stops_201_back;
@property (nonatomic, retain) NSArray * stops_202_go, * stops_202_back;
@property (nonatomic, retain) NSArray * stops_202Shuttle_go, * stops_202Shuttle_back;
@property (nonatomic, retain) NSArray * stops_203_go, * stops_203_back;
@property (nonatomic, retain) NSArray * stops_204_go, * stops_204_back;
@property (nonatomic, retain) NSArray * stops_205_go, * stops_205_back;
@property (nonatomic, retain) NSArray * stops_206_go, * stops_206_back;
@property (nonatomic, retain) NSArray * stops_207_go, * stops_207_back;
@property (nonatomic, retain) NSArray * stops_208_go, * stops_208_back;
@property (nonatomic, retain) NSArray * stops_208Express_go, * stops_208Express_back;
@property (nonatomic, retain) NSArray * stops_208Shuttle_go, * stops_208Shuttle_back;
@property (nonatomic, retain) NSArray * stops_211_go, * stops_211_back;
@property (nonatomic, retain) NSArray * stops_212_go, * stops_212_back;
@property (nonatomic, retain) NSArray * stops_212Shuttle_go, * stops_212Shuttle_back;
@property (nonatomic, retain) NSArray * stops_212Express_go, * stops_212Express_back;
@property (nonatomic, retain) NSArray * stops_212Night_go, * stops_212Night_back;
@property (nonatomic, retain) NSArray * stops_214_go, * stops_214_back;
@property (nonatomic, retain) NSArray * stops_214Express_go, * stops_214Express_back;
@property (nonatomic, retain) NSArray * stops_215_go, * stops_215_back;
@property (nonatomic, retain) NSArray * stops_216Shuttle_go, * stops_216Shuttle_back;
@property (nonatomic, retain) NSArray * stops_216Sub_go, * stops_216Sub_back;
@property (nonatomic, retain) NSArray * stops_218_go, * stops_218_back;
@property (nonatomic, retain) NSArray * stops_218Express_go, * stops_218Express_back;
@property (nonatomic, retain) NSArray * stops_218Shuttle_go, * stops_218Shuttle_back;
@property (nonatomic, retain) NSArray * stops_220_go, * stops_220_back;
@property (nonatomic, retain) NSArray * stops_220Express_go, * stops_220Express_back;
@property (nonatomic, retain) NSArray * stops_220Night_go, * stops_220Night_back;
@property (nonatomic, retain) NSArray * stops_221_go, * stops_221_back;
@property (nonatomic, retain) NSArray * stops_222_go, * stops_222_back;
@property (nonatomic, retain) NSArray * stops_223_go, * stops_223_back;
@property (nonatomic, retain) NSArray * stops_224_go, * stops_224_back;
@property (nonatomic, retain) NSArray * stops_225_go, * stops_225_back;
@property (nonatomic, retain) NSArray * stops_225Shuttle_go, * stops_225Shuttle_back;
@property (nonatomic, retain) NSArray * stops_226_go, * stops_226_back;
@property (nonatomic, retain) NSArray * stops_227_go, * stops_227_back;
@property (nonatomic, retain) NSArray * stops_227Shuttle_go, * stops_227Shuttle_back;
@property (nonatomic, retain) NSArray * stops_230_go, * stops_230_back;
@property (nonatomic, retain) NSArray * stops_231_go, * stops_231_back;
@property (nonatomic, retain) NSArray * stops_232_go, * stops_232_back;
@property (nonatomic, retain) NSArray * stops_232Fast_go, * stops_232Fast_back;
@property (nonatomic, retain) NSArray * stops_232Sub_go, * stops_232Sub_back;
@property (nonatomic, retain) NSArray * stops_234_go, * stops_234_back;
@property (nonatomic, retain) NSArray * stops_235_go, * stops_235_back;
@property (nonatomic, retain) NSArray * stops_236_go, * stops_236_back;
@property (nonatomic, retain) NSArray * stops_236Shuttle_go, * stops_236Shuttle_back;
@property (nonatomic, retain) NSArray * stops_236Night_go, * stops_236Night_back;
@property (nonatomic, retain) NSArray * stops_237_go, * stops_237_back;
@property (nonatomic, retain) NSArray * stops_240_go, * stops_240_back;
@property (nonatomic, retain) NSArray * stops_240Express_go, * stops_240Express_back;
@property (nonatomic, retain) NSArray * stops_241_go, * stops_241_back;
@property (nonatomic, retain) NSArray * stops_242_go, * stops_242_back;
@property (nonatomic, retain) NSArray * stops_243_go, * stops_243_back;
@property (nonatomic, retain) NSArray * stops_245_go, * stops_245_back;
@property (nonatomic, retain) NSArray * stops_246_go, * stops_246_back;
@property (nonatomic, retain) NSArray * stops_247_go, * stops_247_back;
@property (nonatomic, retain) NSArray * stops_247Shuttle_go, * stops_247Shuttle_back;
@property (nonatomic, retain) NSArray * stops_248_go, * stops_248_back;
@property (nonatomic, retain) NSArray * stops_249_go, * stops_249_back;
@property (nonatomic, retain) NSArray * stops_250_go, * stops_250_back;
@property (nonatomic, retain) NSArray * stops_251_go, * stops_251_back;
@property (nonatomic, retain) NSArray * stops_251Shuttle_go, * stops_251Shuttle_back;
@property (nonatomic, retain) NSArray * stops_252_go, * stops_252_back;
@property (nonatomic, retain) NSArray * stops_253_go, * stops_253_back;
@property (nonatomic, retain) NSArray * stops_254_go, * stops_254_back;
@property (nonatomic, retain) NSArray * stops_255_go, * stops_255_back;
@property (nonatomic, retain) NSArray * stops_255Shuttle_go, * stops_255Shuttle_back;
@property (nonatomic, retain) NSArray * stops_256_go, * stops_256_back;
@property (nonatomic, retain) NSArray * stops_257_go, * stops_257_back;
@property (nonatomic, retain) NSArray * stops_260_go, * stops_260_back;
@property (nonatomic, retain) NSArray * stops_260Shuttle_go, * stops_260Shuttle_back;
@property (nonatomic, retain) NSArray * stops_261_go, * stops_261_back;
@property (nonatomic, retain) NSArray * stops_262_go, * stops_262_back;
@property (nonatomic, retain) NSArray * stops_262Shuttle_go, * stops_262Shuttle_back;
@property (nonatomic, retain) NSArray * stops_263_go, * stops_263_back;
@property (nonatomic, retain) NSArray * stops_265Central_go, * stops_265Central_back;
@property (nonatomic, retain) NSArray * stops_265Mingde_go, * stops_265Mingde_back;
@property (nonatomic, retain) NSArray * stops_265Shuttle_go, * stops_265Shuttle_back;
@property (nonatomic, retain) NSArray * stops_265Night_go, * stops_265Night_back;
@property (nonatomic, retain) NSArray * stops_266_go, * stops_266_back;
@property (nonatomic, retain) NSArray * stops_266Shuttle_go, * stops_266Shuttle_back;
@property (nonatomic, retain) NSArray * stops_267_go, * stops_267_back;
@property (nonatomic, retain) NSArray * stops_268_go, * stops_268_back;
@property (nonatomic, retain) NSArray * stops_270_go, * stops_270_back;
@property (nonatomic, retain) NSArray * stops_270Shuttle_go, * stops_270Shuttle_back;
@property (nonatomic, retain) NSArray * stops_274_go, * stops_274_back;
@property (nonatomic, retain) NSArray * stops_276_go, * stops_276_back;
@property (nonatomic, retain) NSArray * stops_277_go, * stops_277_back;
@property (nonatomic, retain) NSArray * stops_278_go, * stops_278_back;
@property (nonatomic, retain) NSArray * stops_278Shuttle_go, * stops_278Shuttle_back;
@property (nonatomic, retain) NSArray * stops_279_go, * stops_279_back;
@property (nonatomic, retain) NSArray * stops_280_go, * stops_280_back;
@property (nonatomic, retain) NSArray * stops_280Express_go, * stops_280Express_back;
@property (nonatomic, retain) NSArray * stops_281_go, * stops_281_back;
@property (nonatomic, retain) NSArray * stops_282_go, * stops_282_back;
@property (nonatomic, retain) NSArray * stops_282Sub_go, * stops_282Sub_back;
@property (nonatomic, retain) NSArray * stops_284_go, * stops_284_back;
@property (nonatomic, retain) NSArray * stops_284Express_go, * stops_284Express_back;
@property (nonatomic, retain) NSArray * stops_285_go, * stops_285_back;
@property (nonatomic, retain) NSArray * stops_286_go, * stops_286_back;
@property (nonatomic, retain) NSArray * stops_286Sub_go, * stops_286Sub_back;
@property (nonatomic, retain) NSArray * stops_287_go, * stops_287_back;
@property (nonatomic, retain) NSArray * stops_287Night_go, * stops_287Night_back;
@property (nonatomic, retain) NSArray * stops_287Shuttle_go, * stops_287Shuttle_back;
@property (nonatomic, retain) NSArray * stops_288_go, * stops_288_back;
@property (nonatomic, retain) NSArray * stops_288Shuttle_go, * stops_288Shuttle_back;
@property (nonatomic, retain) NSArray * stops_290_go, * stops_290_back;
@property (nonatomic, retain) NSArray * stops_290Sub_go, * stops_290Sub_back;
@property (nonatomic, retain) NSArray * stops_292_go, * stops_292_back;
@property (nonatomic, retain) NSArray * stops_292Sub_go, * stops_292Sub_back;
@property (nonatomic, retain) NSArray * stops_294_go, * stops_294_back;
@property (nonatomic, retain) NSArray * stops_295_go, * stops_295_back;
@property (nonatomic, retain) NSArray * stops_297_go, * stops_297_back;
@property (nonatomic, retain) NSArray * stops_298_go, * stops_298_back;
@property (nonatomic, retain) NSArray * stops_298Shuttle_go, * stops_298Shuttle_back;
@property (nonatomic, retain) NSArray * stops_299_go, * stops_299_back;
@property (nonatomic, retain) NSArray * stops_299Shuttle_go, * stops_299Shuttle_back;
@property (nonatomic, retain) NSArray * stops_302_go, * stops_302_back;
@property (nonatomic, retain) NSArray * stops_303_go, * stops_303_back;
@property (nonatomic, retain) NSArray * stops_303Shuttle_go, * stops_303Shuttle_back;
@property (nonatomic, retain) NSArray * stops_304Chengde_go, * stops_304Chengde_back;
@property (nonatomic, retain) NSArray * stops_304ChongqingN_go, * stops_304ChongqingN_back;
@property (nonatomic, retain) NSArray * stops_306_go, * stops_306_back;
@property (nonatomic, retain) NSArray * stops_306Shuttle_go, * stops_306Shuttle_back;
@property (nonatomic, retain) NSArray * stops_307_go, * stops_307_back;
@property (nonatomic, retain) NSArray * stops_308_go, * stops_308_back;
@property (nonatomic, retain) NSArray * stops_310_go, * stops_310_back;
@property (nonatomic, retain) NSArray * stops_311_go, * stops_311_back;
@property (nonatomic, retain) NSArray * stops_505_go, * stops_505_back;
@property (nonatomic, retain) NSArray * stops_508_go, * stops_508_back;
@property (nonatomic, retain) NSArray * stops_508Shuttle_go, * stops_508Shuttle_back;
@property (nonatomic, retain) NSArray * stops_513_go, * stops_513_back;
@property (nonatomic, retain) NSArray * stops_518_go, * stops_518_back;
@property (nonatomic, retain) NSArray * stops_520_go, * stops_520_back;
@property (nonatomic, retain) NSArray * stops_521_go, * stops_521_back;
@property (nonatomic, retain) NSArray * stops_527_go, * stops_527_back;
@property (nonatomic, retain) NSArray * stops_529_go, * stops_529_back;
@property (nonatomic, retain) NSArray * stops_530_go, * stops_530_back;
@property (nonatomic, retain) NSArray * stops_531_go, * stops_531_back;
@property (nonatomic, retain) NSArray * stops_535_go, * stops_535_back;
@property (nonatomic, retain) NSArray * stops_536_go, * stops_536_back;
@property (nonatomic, retain) NSArray * stops_537_go, * stops_537_back;
@property (nonatomic, retain) NSArray * stops_539_go, * stops_539_back;
@property (nonatomic, retain) NSArray * stops_542_go, * stops_542_back;
@property (nonatomic, retain) NSArray * stops_550_go, * stops_550_back;
@property (nonatomic, retain) NSArray * stops_551_go, * stops_551_back;
@property (nonatomic, retain) NSArray * stops_552_go, * stops_552_back;
@property (nonatomic, retain) NSArray * stops_553_go, * stops_553_back;
@property (nonatomic, retain) NSArray * stops_555_go, * stops_555_back;
@property (nonatomic, retain) NSArray * stops_556_go, * stops_556_back;
@property (nonatomic, retain) NSArray * stops_601_go, * stops_601_back;
@property (nonatomic, retain) NSArray * stops_602_go, * stops_602_back;
@property (nonatomic, retain) NSArray * stops_604_go, * stops_604_back;
@property (nonatomic, retain) NSArray * stops_605_go, * stops_605_back;
@property (nonatomic, retain) NSArray * stops_605Fast_go, * stops_605Fast_back;
@property (nonatomic, retain) NSArray * stops_605Sub_go, * stops_605Sub_back;
@property (nonatomic, retain) NSArray * stops_605Xintaiwu_go, * stops_605Xintaiwu_back;
@property (nonatomic, retain) NSArray * stops_606_go, * stops_606_back;
@property (nonatomic, retain) NSArray * stops_611_go, * stops_611_back;
@property (nonatomic, retain) NSArray * stops_612_go, * stops_612_back;
@property (nonatomic, retain) NSArray * stops_612Shuttle_go, * stops_612Shuttle_back;
@property (nonatomic, retain) NSArray * stops_615_go, * stops_615_back;
@property (nonatomic, retain) NSArray * stops_616_go, * stops_616_back;
@property (nonatomic, retain) NSArray * stops_617_go, * stops_617_back;
@property (nonatomic, retain) NSArray * stops_618_go, * stops_618_back;
@property (nonatomic, retain) NSArray * stops_620_go, * stops_620_back;
@property (nonatomic, retain) NSArray * stops_620Shuttle_go, * stops_620Shuttle_back;
@property (nonatomic, retain) NSArray * stops_621_go, * stops_621_back;
@property (nonatomic, retain) NSArray * stops_622_go, * stops_622_back;
@property (nonatomic, retain) NSArray * stops_624_go, * stops_624_back;
@property (nonatomic, retain) NSArray * stops_629_go, * stops_629_back;
@property (nonatomic, retain) NSArray * stops_630_go, * stops_630_back;
@property (nonatomic, retain) NSArray * stops_631_go, * stops_631_back;
@property (nonatomic, retain) NSArray * stops_632_go, * stops_632_back;
@property (nonatomic, retain) NSArray * stops_635_go, * stops_635_back;
@property (nonatomic, retain) NSArray * stops_635Sub_go, * stops_635Sub_back;
@property (nonatomic, retain) NSArray * stops_636_go, * stops_636_back;
@property (nonatomic, retain) NSArray * stops_637_go, * stops_637_back;
@property (nonatomic, retain) NSArray * stops_638_go, * stops_638_back;
@property (nonatomic, retain) NSArray * stops_639_go, * stops_639_back;
@property (nonatomic, retain) NSArray * stops_640_go, * stops_640_back;
@property (nonatomic, retain) NSArray * stops_641_go, * stops_641_back;
@property (nonatomic, retain) NSArray * stops_642_go, * stops_642_back;
@property (nonatomic, retain) NSArray * stops_643_go, * stops_643_back;

// ---------------------------------------------------- //

@property (nonatomic, retain) NSArray * stops_644_go, * stops_644_back;
@property (nonatomic, retain) NSArray * stops_645_go, * stops_645_back;
@property (nonatomic, retain) NSArray * stops_645Sub_go, * stops_645Sub_back;
@property (nonatomic, retain) NSArray * stops_646_go, * stops_646_back;
@property (nonatomic, retain) NSArray * stops_646Shuttle_go, * stops_646Shuttle_back;
@property (nonatomic, retain) NSArray * stops_647_go, * stops_647_back;
@property (nonatomic, retain) NSArray * stops_648_go, * stops_648_back;
@property (nonatomic, retain) NSArray * stops_650_go, * stops_650_back;
@property (nonatomic, retain) NSArray * stops_651_go, * stops_651_back;
@property (nonatomic, retain) NSArray * stops_652_go, * stops_652_back;
@property (nonatomic, retain) NSArray * stops_656_go, * stops_656_back;
@property (nonatomic, retain) NSArray * stops_657_go, * stops_657_back;
@property (nonatomic, retain) NSArray * stops_658_go, * stops_658_back;
@property (nonatomic, retain) NSArray * stops_659_go, * stops_659_back;
@property (nonatomic, retain) NSArray * stops_660_go, * stops_660_back;
@property (nonatomic, retain) NSArray * stops_662_go, * stops_662_back;
@property (nonatomic, retain) NSArray * stops_663_go, * stops_663_back;
@property (nonatomic, retain) NSArray * stops_665_go, * stops_665_back;
@property (nonatomic, retain) NSArray * stops_666_go, * stops_666_back;
@property (nonatomic, retain) NSArray * stops_667_go, * stops_667_back;
@property (nonatomic, retain) NSArray * stops_668_go, * stops_668_back;
@property (nonatomic, retain) NSArray * stops_669_go, * stops_669_back;
@property (nonatomic, retain) NSArray * stops_670_go, * stops_670_back;
@property (nonatomic, retain) NSArray * stops_671_go, * stops_671_back;
@property (nonatomic, retain) NSArray * stops_672_go, * stops_672_back;
@property (nonatomic, retain) NSArray * stops_672Shuttle_go, * stops_672Shuttle_back;
@property (nonatomic, retain) NSArray * stops_673_go, * stops_673_back;
@property (nonatomic, retain) NSArray * stops_675_go, * stops_675_back;
@property (nonatomic, retain) NSArray * stops_676_go, * stops_676_back;
@property (nonatomic, retain) NSArray * stops_677_go, * stops_677_back;
@property (nonatomic, retain) NSArray * stops_678_go, * stops_678_back;
@property (nonatomic, retain) NSArray * stops_679_go, * stops_679_back;
@property (nonatomic, retain) NSArray * stops_680_go, * stops_680_back;
@property (nonatomic, retain) NSArray * stops_681_go, * stops_681_back;
@property (nonatomic, retain) NSArray * stops_685_go, * stops_685_back;
@property (nonatomic, retain) NSArray * stops_701_go, * stops_701_back;
@property (nonatomic, retain) NSArray * stops_702_go, * stops_702_back;
@property (nonatomic, retain) NSArray * stops_705_go, * stops_705_back;
@property (nonatomic, retain) NSArray * stops_706_go, * stops_706_back;
@property (nonatomic, retain) NSArray * stops_711_go, * stops_711_back;
@property (nonatomic, retain) NSArray * stops_756_go, * stops_756_back;
@property (nonatomic, retain) NSArray * stops_902_go, * stops_902_back;
@property (nonatomic, retain) NSArray * stops_903_go, * stops_903_back;
@property (nonatomic, retain) NSArray * stops_905_go, * stops_905_back;
@property (nonatomic, retain) NSArray * stops_905Sub_go, * stops_905Sub_back;
@property (nonatomic, retain) NSArray * stops_906_go, * stops_906_back;
@property (nonatomic, retain) NSArray * stops_906Sub_go, * stops_906Sub_back;
@property (nonatomic, retain) NSArray * stops_907_go, * stops_907_back;
@property (nonatomic, retain) NSArray * stops_909_go, * stops_909_back;
@property (nonatomic, retain) NSArray * stops_912_go, * stops_912_back;
@property (nonatomic, retain) NSArray * stops_915_go, * stops_915_back;
@property (nonatomic, retain) NSArray * stops_M1_go, * stops_M1_back;
@property (nonatomic, retain) NSArray * stops_M2_go, * stops_M2_back;
@property (nonatomic, retain) NSArray * stops_M3_go, *stops_M3_back;
@property (nonatomic, retain) NSArray * stops_M5_go, * stops_M5_back;
@property (nonatomic, retain) NSArray * stops_M6_go, * stops_M6_back;
@property (nonatomic, retain) NSArray * stops_M7_go, * stops_M7_back;
@property (nonatomic, retain) NSArray * stops_M8_go, * stops_M8_back;
@property (nonatomic, retain) NSArray * stops_M9_go, *stops_M9_back;
@property (nonatomic, retain) NSArray * stops_M10_go, * stops_M10_back;
@property (nonatomic, retain) NSArray * stops_M11_go, * stops_M11_back;
@property (nonatomic, retain) NSArray * stops_M12_go, * stops_M12_back;
@property (nonatomic, retain) NSArray * stops_M15_go, * stops_M15_back;
@property (nonatomic, retain) NSArray * stops_JingmeiTVGHExp_go, * stops_JingmeiTVGHExp_back;
@property (nonatomic, retain) NSArray * stops_MaokongRight_go, * stops_MaokongRight_back;
@property (nonatomic, retain) NSArray * stops_MaokongLeftZoo_go;
@property (nonatomic, retain) NSArray * stops_MaokongLeftTemple_go, * stops_MaokongLeftTemple_back;
@property (nonatomic, retain) NSArray * stops_NKTianMu_go, * stops_NKTianMu_back;
@property (nonatomic, retain) NSArray * stops_NKBeiTou_go, * stops_NKBeiTou_back;
@property (nonatomic, retain) NSArray * stops_NKZhongheNKSBP_go, * stops_NKZhongheNKSBP_back;
@property (nonatomic, retain) NSArray * stops_NKShuanghe_go, * stops_NKShuanghe_back;
@property (nonatomic, retain) NSArray * stops_S31_Gong_go, * stops_S31_Gong_back;
@property (nonatomic, retain) NSArray * stops_S31_Chong_go, * stops_S31_Chong_back;
@property (nonatomic, retain) NSArray * stops_S1_go, * stops_S1_back;
@property (nonatomic, retain) NSArray * stops_S1Shuttle_go, * stops_S1Shuttle_back;
@property (nonatomic, retain) NSArray * stops_S2_go, * stops_S2_back;
@property (nonatomic, retain) NSArray * stops_S2Shuttle_go, * stops_S2Shuttle_back;
@property (nonatomic, retain) NSArray * stops_S3_go, * stops_S3_back;
@property (nonatomic, retain) NSArray * stops_S3Shuttle_go, * stops_S3Shuttle_back;
@property (nonatomic, retain) NSArray * stops_S5_go, * stops_S5_back;
@property (nonatomic, retain) NSArray * stops_S5Shuttle_go, * stops_S5Shuttle_back;
@property (nonatomic, retain) NSArray * stops_S6_go, * stops_S6_back;
@property (nonatomic, retain) NSArray * stops_S7_go, * stops_S7_back;
@property (nonatomic, retain) NSArray * stops_S8_go, * stops_S8_back;
@property (nonatomic, retain) NSArray * stops_S9_go, * stops_S9_back;
@property (nonatomic, retain) NSArray * stops_S10_go, * stops_S10_back;
@property (nonatomic, retain) NSArray * stops_S11_go, * stops_S11_back;
@property (nonatomic, retain) NSArray * stops_S12_go, * stops_S12_back;
@property (nonatomic, retain) NSArray * stops_S12Shuttle_go, * stops_S12Shuttle_back;
@property (nonatomic, retain) NSArray * stops_S14_go, * stops_S14_back;
@property (nonatomic, retain) NSArray * stops_S15_go, * stops_S15_back;
@property (nonatomic, retain) NSArray * stops_S15Shuttle_go, * stops_S15Shuttle_back;
@property (nonatomic, retain) NSArray * stops_S16_go, * stops_S16_back;
@property (nonatomic, retain) NSArray * stops_S17_go, * stops_S17_back;
@property (nonatomic, retain) NSArray * stops_S18_go, * stops_S18_back;
@property (nonatomic, retain) NSArray * stops_S18Shuttle_go, * stops_S18Shuttle_back;
@property (nonatomic, retain) NSArray * stops_S19_go, * stops_S19_back;
@property (nonatomic, retain) NSArray * stops_S21_go, * stops_S21_back;
@property (nonatomic, retain) NSArray * stops_S22_go, * stops_S22_back;
@property (nonatomic, retain) NSArray * stops_S23_go, * stops_S23_back;
@property (nonatomic, retain) NSArray * stops_S25_go, * stops_S25_back;
@property (nonatomic, retain) NSArray * stops_S26_go, * stops_S26_back;
@property (nonatomic, retain) NSArray * stops_S28_go, * stops_S28_back;
@property (nonatomic, retain) NSArray * stops_Dunhua_go, * stops_Dunhua_back;
@property (nonatomic, retain) NSArray * stops_ZhongxiaoNML_go, * stops_ZhongxiaoNML_back;
@property (nonatomic, retain) NSArray * stops_HepingML_go, * stops_HepingML_back;
@property (nonatomic, retain) NSArray * stops_XinYiNML_go, * stops_XinYiNML_back;
@property (nonatomic, retain) NSArray * stops_BoaiShuttle_go, * stops_BoaiShuttle_back;
@property (nonatomic, retain) NSArray * stops_XinYiML_go, * stops_XinYiML_back;
@property (nonatomic, retain) NSArray * stops_XinYiSub_go, * stops_XinYiSub_back;
@property (nonatomic, retain) NSArray * stops_ZhongshanML_go, * stops_ZhongshanML_back;
@property (nonatomic, retain) NSArray * stops_ChongqingML_go, * stops_ChongqingML_back;
@property (nonatomic, retain) NSArray * stops_NH1_go, * stops_NH1_back;
@property (nonatomic, retain) NSArray * stops_NH2_go, * stops_NH2_back;
@property (nonatomic, retain) NSArray * stops_NH3_go, * stops_NH3_back;
@property (nonatomic, retain) NSArray * stops_NH5_go, * stops_NH5_back;
@property (nonatomic, retain) NSArray * stops_NH6_go, * stops_NH6_back;
@property (nonatomic, retain) NSArray * stops_NH7_go, * stops_NH7_back;
@property (nonatomic, retain) NSArray * stops_NH8_go, * stops_NH8_back;
@property (nonatomic, retain) NSArray * stops_NH9_go, * stops_NH9_back;
@property (nonatomic, retain) NSArray * stops_NH10_go, * stops_NH10_back;
@property (nonatomic, retain) NSArray * stops_NH11_go, * stops_NH11_back;
@property (nonatomic, retain) NSArray * stops_NH12_go, * stops_NH12_back;
@property (nonatomic, retain) NSArray * stops_NH13_go, * stops_NH13_back;
@property (nonatomic, retain) NSArray * stops_NH15_go, * stops_NH15_back;
@property (nonatomic, retain) NSArray * stops_NH16_go, * stops_NH16_back;
@property (nonatomic, retain) NSArray * stops_NH17_go, * stops_NH17_back;
@property (nonatomic, retain) NSArray * stops_NH18_go, * stops_NH18_back;
@property (nonatomic, retain) NSArray * stops_NH19_go, * stops_NH19_back;
@property (nonatomic, retain) NSArray * stops_NH20_go, * stops_NH20_back;
@property (nonatomic, retain) NSArray * stops_MRTYSNehuExp_go, * stops_MRTYSNehuExp_back;
@property (nonatomic, retain) NSArray * stops_TaipeiCityHall_go, * stops_TaipeiCityHall_back;
// ------- 接駁公車-------------------
@property (nonatomic, retain) NSArray * stops_R2_go, * stops_R2_back;
@property (nonatomic, retain) NSArray * stops_R3_go, * stops_R3_back;
@property (nonatomic, retain) NSArray * stops_R5_go, * stops_R5_back;
@property (nonatomic, retain) NSArray * stops_R7_go, * stops_R7_back;
@property (nonatomic, retain) NSArray * stops_R7Section_go, * stops_R7Section_back;
@property (nonatomic, retain) NSArray * stops_R9_go, * stops_R9_back;
@property (nonatomic, retain) NSArray * stops_R10_go, * stops_R10_back;
@property (nonatomic, retain) NSArray * stops_R12_go, * stops_R12_back;
@property (nonatomic, retain) NSArray * stops_R15_go, * stops_R15_back;
@property (nonatomic, retain) NSArray * stops_R19_go, * stops_R19_back;
@property (nonatomic, retain) NSArray * stops_R25_go, * stops_R25_back;
@property (nonatomic, retain) NSArray * stops_R29_go, * stops_R29_back;
@property (nonatomic, retain) NSArray * stops_R30_go, * stops_R30_back;
@property (nonatomic, retain) NSArray * stops_R31_go, * stops_R31_back;
@property (nonatomic, retain) NSArray * stops_R32_go, * stops_R32_back;
@property (nonatomic, retain) NSArray * stops_R33_go, * stops_R33_back;
@property (nonatomic, retain) NSArray * stops_R34_go, * stops_R34_back;
@property (nonatomic, retain) NSArray * stops_R35_go, * stops_R35_back;
@property (nonatomic, retain) NSArray * stops_R50_go, * stops_R50_back;
@property (nonatomic, retain) NSArray * stops_B2_go, * stops_B2_back;
@property (nonatomic, retain) NSArray * stops_B5_go, * stops_B5_back;
@property (nonatomic, retain) NSArray * stops_B7_go, * stops_B7_back;
@property (nonatomic, retain) NSArray * stops_B10_go, * stops_B10_back;
@property (nonatomic, retain) NSArray * stops_B12_go, * stops_B12_back;
@property (nonatomic, retain) NSArray * stops_B20Section_go, * stops_B20Section_back;
@property (nonatomic, retain) NSArray * stops_B25_go, * stops_B25_back;
@property (nonatomic, retain) NSArray * stops_B26_go, * stops_B26_back;
@property (nonatomic, retain) NSArray * stops_B27_go, * stops_B27_back;
@property (nonatomic, retain) NSArray * stops_B28_go, * stops_B28_back;
@property (nonatomic, retain) NSArray * stops_B29_go, * stops_B29_back;
@property (nonatomic, retain) NSArray * stops_B36_go, * stops_B36_back;
@property (nonatomic, retain) NSArray * stops_B50_go, * stops_B50_back;
@property (nonatomic, retain) NSArray * stops_B51_go, * stops_B51_back;
@property (nonatomic, retain) NSArray * stops_BR1_go, * stops_BR1_back;
@property (nonatomic, retain) NSArray * stops_BR2_go, * stops_BR2_back;
@property (nonatomic, retain) NSArray * stops_BR3_go, * stops_BR3_back;
@property (nonatomic, retain) NSArray * stops_BR5_go, * stops_BR5_back;
@property (nonatomic, retain) NSArray * stops_BR6_go, * stops_BR6_back;
@property (nonatomic, retain) NSArray * stops_BR7_go, * stops_BR7_back;
@property (nonatomic, retain) NSArray * stops_BR9_go, * stops_BR9_back;
@property (nonatomic, retain) NSArray * stops_BR10_go, * stops_BR10_back;
@property (nonatomic, retain) NSArray * stops_BR11_go, * stops_BR11_back;
@property (nonatomic, retain) NSArray * stops_BR11Sub_go, * stops_BR11Sub_back;
@property (nonatomic, retain) NSArray * stops_BR12_go, * stops_BR12_back;
@property (nonatomic, retain) NSArray * stops_BR13_go, * stops_BR13_back;
@property (nonatomic, retain) NSArray * stops_BR15_go, * stops_BR15_back;
@property (nonatomic, retain) NSArray * stops_BR15Shuttle_go, * stops_BR15Shuttle_back;
@property (nonatomic, retain) NSArray * stops_BR16_go, * stops_BR16_back;
@property (nonatomic, retain) NSArray * stops_BR18_go, * stops_BR18_back;
@property (nonatomic, retain) NSArray * stops_BR19_go, * stops_BR19_back;
@property (nonatomic, retain) NSArray * stops_BR20_go, * stops_BR20_back;
@property (nonatomic, retain) NSArray * stops_BR21_go, * stops_BR21_back;
@property (nonatomic, retain) NSArray * stops_G1_go, * stops_G1_back;
@property (nonatomic, retain) NSArray * stops_G2L_go, * stops_G2L_back;
@property (nonatomic, retain) NSArray * stops_G2R_go, * stops_G2R_back;
@property (nonatomic, retain) NSArray * stops_G11_go, * stops_G11_back;
// ------------------------------------------------------
@property (nonatomic, retain) NSArray * estimatetime;
// ------------------------------------------------------
@property (nonatomic, retain) NSArray * section0Zh, * section1Zh, * section2Zh, * section3Zh, * section4Zh, * section5Zh, * section6Zh, * section7Zh, * section8Zh, * section9Zh, * section10Zh, * section11Zh, * section12Zh, * section13Zh, * section14Zh;
@property (nonatomic, retain) NSArray * section0En, * section1En, * section2En, * section3En, * section4En, * section5En, * section6En, * section7En, * section8En, * section9En, * section10En, * section11En, * section12En, * section13En, * section14En;
@property (nonatomic, retain) NSArray * section0Depart, * section1Depart, * section2Depart, * section3Depart, * section4Depart, * section5Depart, * section6Depart, * section7Depart, * section8Depart, * section9Depart, * section10Depart, * section11Depart, * section12Depart, * section13Depart, * section14Depart;
@property (nonatomic, retain) NSArray * section0Destin, * section1Destin, * section2Destin, * section3Destin, * section4Destin, * section5Destin, * section6Destin, * section7Destin, * section8Destin, * section9Destin, * section10Destin, * section11Destin, * section12Destin, * section13Destin, * section14Destin;

@property (nonatomic, retain) IBOutlet UITableView * table;
@property (nonatomic, retain) IBOutlet UISearchBar * search;
@property (nonatomic, retain) NSDictionary * allData;
@property (nonatomic, retain) NSMutableDictionary * searchData;
@property (nonatomic, retain) NSArray * allKeys;
@property (nonatomic, retain) NSMutableArray * keys;

- (void) resetSearch;
- (void) handleSearchForTerm:(NSString *)searchTerm;

@end

